### ISSUE TITLE
Same Video uploaded as long length video of whole section 

### ISSUE THREAD

**Issue by jmakwana01** [Cyfrin/foundry-full-course-cu#2023]
### Section

Section 10 | ERC20s

### Could you please leave a link to the Cyfrin Updraft Lesson (or YouTube video timestamp) where this error occurs? (You can right click a video and "copy video URL at current time")

https://updraft.cyfrin.io/courses/advanced-foundry/How-to-create-an-erc20-crypto-currency/erc20-ai-tests-and-recap?lesson_format=video

### Describe the bug

![image](https://github.com/user-attachments/assets/03d555fb-60a3-4ec4-b0e0-c1d2a4963bf2)

section 1
subsection 6 is basically the whole section from the start as a compilation

**Comment by cromewar** [comment]
Thanks @jmakwana01  and @EngrPips I will take care of this from the dev environment

**Comment by EngrPips** [comment]
Thanks for all you do, sir @cromewar.
