### ISSUE TITLE
Please correct video at these Timestamps these 

### ISSUE THREAD

**Issue by ayesparshh** [Cyfrin/foundry-full-course-cu#2080]
### Section

Section 6 | Foundry Simple Storage

### Describe the bug

![Screenshot 2024-07-22 203540](https://github.com/user-attachments/assets/8174b83b-b7b5-4868-bea4-e8eff474ebe9)
![Screenshot 2024-07-22 203556](https://github.com/user-attachments/assets/4852eb40-6a02-469d-8af1-e1a97f9e7b14)
![Screenshot 2024-07-22 203608](https://github.com/user-attachments/assets/d089337f-9f2b-4789-b23f-b6d9f66bb22a)
![Screenshot 2024-07-22 214550](https://github.com/user-attachments/assets/75fb557a-5083-4767-9131-c6faa166f72f)

**Comment by EngrPips** [comment]
Hey @ayesparshh, This will be attended to appropriately as soon as possible.

**Comment by cromewar** [comment]
Hello @ayesparshh, we are aware of this problem, and it seems to be because of corruption on the video uploaded to YouTube, so we might re-upload it. Can you please continue the course on https://updraft.cyfrin.io/, it's free.
