### ISSUE TITLE
Video subtitle position

### ISSUE THREAD

**Issue by ItsAnkitPatel** [Cyfrin/foundry-full-course-cu#2182]
Is it possible to change how subtitle shows ?

Like right now at this moment they actually get hidden behind the player if I hit pause or play.

![image](https://github.com/user-attachments/assets/2f3da692-2513-41e8-b026-619c5edf7213)

It would be better if we can have subtitles dynamic position just like youtube which is always above the vide player controls.

I can do that too if you want. 
What step I need to do to make this PR like any separate repo for this video player functionality ?(just asking, it's fine if there is no way)

**Comment by cromewar** [comment]
Thanks for this recommendation I will bring this to our developer team eyes, you are a rockstar!
