### ISSUE TITLE
.ENV Pledge and keystore management

### ISSUE THREAD

**Issue by bxpana** [Cyfrin/foundry-full-course-cu#2203]
### Section

Section 6 | Foundry Simple Storage

### Could you please leave a link to the Cyfrin Updraft Lesson (or YouTube video timestamp) where this error occurs? (You can right click a video and "copy video URL at current time")

https://updraft.cyfrin.io/courses/foundry/foundry-simple-storage/private-key-safety-part-2?lesson_format=video

### Describe the bug

In the [.ENV Pledge](https://github.com/Cyfrin/foundry-full-course-cu/discussions/5#discussion-5167849) it says that Foundry does not have their own keystore creator, but from the Foundry Github issue that @PatrickAlphaC [mentioned](https://github.com/foundry-rs/foundry/issues/1869) and https://github.com/foundry-rs/foundry/issues/3818 it seems to be implemented. 

If so, then I think the .ENV Pledge and the video should be updated for users to be able to use the Keystore function on Foundry similar to [this](https://docs.zksync.io/build/start-coding/zksync-101#private-key-setup-with-foundry-keystore)

**Comment by bxpana** [comment]
Ok immediately after there is the update video to not use .env files anymore https://updraft.cyfrin.io/courses/foundry/foundry-simple-storage/never-use-a-env-file?lesson_format=video

But I think would still be good to update the pledge

**Comment by EngrPips** [comment]
Thanks for pointing this out and it will attended to appropriately as soon as possible.

**Comment by PatrickAlphaC** [comment]
Updated :)
