### ISSUE TITLE
Video restarts when I open another window above it

### ISSUE THREAD

**Issue by doretox** [Cyfrin/foundry-full-course-cu#2205]
### Section

Section 1 | Blockchain Basics

### Describe the bug

If I'm watching any video, and decide to change my browser to the Discord app, the video I'm watching starts again.

I hope this issue is placed in the right place. Thanks for the content and initiative.

**Comment by RoccoAlfano** [comment]
Having the same problem

**Comment by cromewar** [comment]
We are researching the possible cause of the issue and will try to fix it as soon as possible. 

Thanks @doretox and @RoccoAlfano

**Comment by cromewar** [comment]
Can you be more detailed @doretox, do you close the Cyfrin tab and open it again, or leave it open and just change the app?

**Comment by doretox** [comment]
I left it open and just open another app

**Comment by cromewar** [comment]
FIx is complete. Thanks for the feedback. Please reload Updraft, and It should be fixed.
