### ISSUE TITLE
Duplicate Congratulations part 14 and part 20 after course update

### ISSUE THREAD

**Issue by Noureketh** [Cyfrin/foundry-full-course-cu#2271]
### Section

Section 1 | Blockchain Basics

### Describe the bug

Part 14 Blockchain overview at 19:00 should be cut off as its the same part as 20 Congratulations - since there is the L2, Rollup updates now

**Comment by EngrPips** [comment]
Thanks for the contribution @Noureketh, This will be attended to appropriately as soon as possible.
