### ISSUE TITLE
Section 1: Solidity Developer  zk Plugin chapter and plugin fix ordering fix

### ISSUE THREAD

**Issue by Noureketh** [Cyfrin/foundry-full-course-cu#2272]
### Section

Section 2 | Simple Storage

### Describe the bug

Solidity smart contract development these two are switched the zk plugin fix chapter is before the plugin itself
![image](https://github.com/user-attachments/assets/33c382b5-62dc-447c-a9e7-bb5ae4019df6)

**Comment by EngrPips** [comment]
Hello @Noureketh, Thanks for the contribution and this will be attended to appropriately as soon as possible.

**Comment by cromewar** [comment]
Thanks a lot for the report; changes were made, @Noureketh.
