### ISSUE TITLE
`testPriceFeedVersionIsAccurate` spelling in Updraft "Update"

### ISSUE THREAD

**Issue by bxpana** [Cyfrin/foundry-full-course-cu#2281]
### Section

Section 7 | Foundry Fund Me

### Could you please leave a link to the Cyfrin Updraft Lesson (or YouTube video timestamp) where this error occurs? (You can right click a video and "copy video URL at current time")

https://updraft.cyfrin.io/courses/foundry/foundry-fund-me/forked-tests?lesson_format=video

### Operating System

None

### Describe the bug

In the Updraft video page, the "Update" has the updated line of code as `testPriced...` instead of `testPrice...` to be inline with what's written in the test file. 
![image](https://github.com/user-attachments/assets/84487ecc-09ec-4647-ae1c-066915ca6c32)

Correct code would be `forge test --mt testPriceFeedVersionIsAccurate -vvvv --fork-url $SEPOLIA_RPC_URL`

**Comment by EngrPips** [comment]
Hello @bxpana, Thanks for this contribution and this will be attended to appropriately as soon as possible.

**Comment by cromewar** [comment]
Thanks for the report, @bxpana. This has been addressed, and changes should be reflected on the platform soon.

**Comment by bxpana** [comment]
Thanks guys!
