### ISSUE TITLE
Foundry Fundamentals: Foundry Installation Windows WSL Video relocation

### ISSUE THREAD

**Issue by Noureketh** [Cyfrin/foundry-full-course-cu#2282]
### Section

Section 6 | Foundry Simple Storage

### Describe the bug

While following the videos on Foundry, there is a huge gap for Windows users  to show the installation of Foundry with its command for WSL and be able to follow through.

The foundry setup is 6  then followed by  7. Setup VSCode and 8. Create Foundry project.
![image](https://github.com/user-attachments/assets/889b6251-028f-46d8-b4e5-6f67ebdcbee9)

so I suggest  edit #6 Foundry Setup (with name update Linux/Mac) description update to remove Windows too to avoid confusion

![image](https://github.com/user-attachments/assets/000556ff-8bfa-4489-b013-d668009fa435)

Also I would suggest checking the order so maybe it goes like this

6. Foundry Setup (Linux/Mac)
7. Foundry Setup (Windows)
7. Setup your VSCode
8. Create a new Foundry project

that way, Windows, Linux & Mac users are going at around the same points together, not 100% but closer than before.

Thank you

**Comment by EngrPips** [comment]
Hello @Noureketh, Thanks for the contribution. This will be addressed appropriately as soon as possible.

**Comment by cromewar** [comment]
Thanks for the recommendation, @Noureketh; we changed the order to something more coherent, and the changes should be reflected on the platform soon.
