### ISSUE TITLE
Need update for lesson 10 “Getting real world price data from Chainlink”

### ISSUE THREAD

**Issue by dovydasradziwill** [Cyfrin/foundry-full-course-cu#2303]
### Section

Section 4 | Fund Me

### Describe the bug

In lesson 10 “Getting real world price data from Chainlink” Section 3 “FundMe” for function getPrice uses old ChainlinkDocs codebase (interface and dataFeed): 
Old version (in video)
![pic1](https://github.com/user-attachments/assets/c93b0aff-e45d-491f-a73c-6ca9594e273e)

Actual code from Chainlink Docs ([Using Data Feeds on EVM Chains | Chainlink Documentation](https://docs.chain.link/data-feeds/using-data-feeds))
AggregatorV3Interface also has difference ([chainlink/contracts/src/v0.8/shared/interfaces/AggregatorV3Interface.sol at develop · smartcontractkit/chainlink (github.com)](https://github.com/smartcontractkit/chainlink/blob/develop/contracts/src/v0.8/shared/interfaces/AggregatorV3Interface.sol))

![pic2](https://github.com/user-attachments/assets/7b35d53b-92c4-4e0b-9224-391b3282cb02)

I wouldn't have focused on this issue if it weren't for the fact that students with a non-technical background (or without basic computer science knowledge) are writing Patrick's code during the course of the course, and as a result, they get an error. And after only half a section on working with Chainlink, the student is more likely to get lost in the massive documentation.

I also draw attention to the fact that the course repository also contains non-working code.

**Comment by EngrPips** [comment]
Hello @dovydasradziwill, Thanks for this contribution and this will be attended to appropriately as soon as possible.

**Comment by cromewar** [comment]
Thanks for the report @dovydasradziwill , we are going to publish and update on this on the lesson.
Should be live in a couple of minutes.
