### ISSUE TITLE
Votes No longer an option inopenzeppelin wizard

### ISSUE THREAD

**Issue by Aletheios42** [Cyfrin/foundry-full-course-cu#2338]
### Section

Section 16 | DAOs

### Could you please leave a link to the Cyfrin Updraft Lesson (or YouTube video timestamp) where this error occurs? (You can right click a video and "copy video URL at current time")

https://updraft.cyfrin.io/courses/advanced-foundry/daos/governance-tokens

### Operating System

Linux

### Describe the bug

import {ERC20Permit} from "@openzeppelin/contracts/token/ERC20/extensions/draft-ERC20Permit.sol";

and that "draft" import no longer a file in openzeppelin

**Comment by EngrPips** [comment]
Hey @Aletheios42, Thanks for this contribution. This will be addressed appropriately as soon as possible.

**Comment by cromewar** [comment]
you are right @Aletheios42 , this was a draft time ago but now is implemented officially, will send and update to the page. 
Thanks for the feedback.
