### ISSUE TITLE
in cyfrin page on the reading section i can't see the gven images can u help me 

### ISSUE THREAD

**Issue by krishno16** [Cyfrin/foundry-full-course-cu#2367]
![Screenshot 2024-09-02 133706](https://github.com/user-attachments/assets/a4aa0db4-935d-4820-bae8-d130297c40c6)

**Comment by EngrPips** [comment]
Hello @krishno16, Thanks for this contribution, and this will be attended to appropriately as soon as possible.

**Comment by cromewar** [comment]
Images problem is already a well known issue and we are working to solve this, thanks for the report @krishno16 

Hope yo have a fix soon.
