### ISSUE TITLE
ETH bridge poblem

### ISSUE THREAD

**Issue by Bamservice47** [Cyfrin/foundry-full-course-cu#2491]
### Discussed in https://github.com/Cyfrin/foundry-full-course-cu/discussions/2489

<div type='discussions-op-text'>

<sup>Originally posted by **ab6955** September 16, 2024</sup>
As patrick showed in the video , I have also bridge some ETH from my **sepolia tesnet** to **zksync sepolia testnet.**
But I haven't received anything still now.
Because of this, I am unable to deploy my contract on zksynck (there is nothing to work on).
So Community, What should I do? </div>

i also get this error code:

Insufficient ETH balance on Ethereum Sepolia Testnet to cover the fee. We recommend having at least 0.001971512456304394 ETH on Ethereum Sepolia Testnet for deposit.

and i have in my metamask 0.0939
SepoliaETH

here is my sETH address: 0xb3f7c120245d92B9c8D3f0edbA59f5a89fc5debb

**Comment by EngrPips** [comment]
Hello @Bamservice47, I will advise that you use the `discussion` tab for this kind of stuff next time, and you should get more sepolia ETH from chainlink faucet https://faucets.chain.link/sepolia and retry. I bridged and didn't run into any issue whatsoever.

**Comment by PatrickAlphaC** [comment]
https://sepolia-era.zksync.network/tx/0x656176def066fa4e768f80f2fbe84140119378ef8fae3991e666cea5bf14dcf9

Shhh, don't tell anyone.
