### ISSUE TITLE
Test Faucet Issue

### ISSUE THREAD

**Issue by JonasAllenCodes** [Cyfrin/foundry-full-course-cu#2643]
### Discussed in https://github.com/Cyfrin/foundry-full-course-cu/discussions/2529

<div type='discussions-op-text'>

<sup>Originally posted by **gyanshupathak** September 22, 2024</sup>
I getting an issue that  i must have 0.01 eth in my mainnet before i can use any of the faucets available in the repo!
How to get that , i just created an metamask account .</div>

**Comment by EngrPips** [comment]
Hello @JonasAllenCodes, This type of discussion is more suitable for the `Discussions` tab of this GitHub page.
