### ISSUE TITLE
Additional explanation needed!

### ISSUE THREAD

**Issue by Tezei** [Cyfrin/foundry-full-course-cu#2707]
### Discussed in https://github.com/Cyfrin/foundry-full-course-cu/discussions/2706

<div type='discussions-op-text'>

<sup>Originally posted by **Tezei** October 18, 2024</sup>
Hello,
Thank you for awesome training and explanations.

I want to suggest a little improvement on this video - https://updraft.cyfrin.io/courses/foundry/foundry-simple-storage/create-new-foundry-setup

When a user uses Windows like me there is no previous explanation of using commands in VS Code, i.e. "forge init". I am getting "Unknown command". And it is normal. Because Foundry is installed not on Windows, but on WSL.

So, I am suggesting to include in this video suggestion to activate WSL in a VS Code terminal first and then go to "mnt" folder and then to c:\ or else and run "forge init" in a project folder. Or using another technique in your opinion, but definitely additional instructions are needed on this stage.

Also, when I tried to compile directly from VS Code on Windows I got "forge not found" and when I tried to compile outside in the directory I got "Error (6275): Source "src/Counter.sol" not found: File not found. "

**Important:** Also, when we are restarting VS Code we received following error "Couldn't find forge binary..." So, maybe it is now suitable to use WSL for Windows users.

Best regards!

</div>

**Comment by EngrPips** [comment]
Hello @Tezei, Thanks for this contribution. This will be attended to appropriately as soon as possible.

**Comment by Tezei** [comment]
> Hello @Tezei, Thanks for this contribution. This will be attended to appropriately as soon as possible.

No problem! I am still struggling what to do to add path to forge binary (usually locates in c:\Users\user\.foundry\bin ) in VS Code. :( I read toml options to add in foundry.toml file but I didn't find any. If you have ideas please advise. :) 

My useful findings so far. 

1. Under Windows use Git Bash which is installed by default Git installation. And then run "curl -L https://foundry.paradigm.xyz | bash" command and then run "foundryup".
2. Under VS Code you can type "ubuntu" command and this activates WSL and via WSL you can use forge commands. But, first you need to navigate to upper mnt folder and then into Windows file system.
3. Another idea of mine is to suggest .vscode folder configuration json files - launch.json, settings.json, tasks,json....

These are critical.

Glad to contribute! 10x a lot.

**Comment by Equious** [comment]
Please move support requests to an appropriate channel (Discussions or Discord).

Appreciate the feedback.
