### ISSUE TITLE
Cannot verify a smart contract on Etherscan 

### ISSUE THREAD

**Issue by 0xdavinci** [Cyfrin/foundry-full-course-cu#2744]
I deployed the smart contract on Sepolia.
My contract used solidity 0.8.28 .
Here is my contract address.
https://sepolia.etherscan.io/address/0x69be1adb241e9215633f48fee8d7532da77c83d0
I tried to verify and publish my contract source code.
I set the Compiler Version to v0.8.28+commit.7893614a.
![Screenshot 2024-10-24 220437](https://github.com/user-attachments/assets/49335c8c-7c47-451f-b08f-d565b4ebea65)

Error! Unable to generate Contract Bytecode and ABI

**Comment by EngrPips** [comment]
Hello @0xdavinci, This type of discussion is appropriate for the `discussion` tab of this GitHub repo and not this `issue` section.
