### ISSUE TITLE
Make install not working

### ISSUE THREAD

**Issue by Tezei** [Cyfrin/foundry-full-course-cu#2784]
### Describe the enhancement

Hiya guys,
According to **Section 4 at Foundry Fundamentals with Smart Contract Lottery** when a beginner clones the repo related to the section and try to run **make install** command it fails. As a beginner at first time I was a little bit confused, but I looked in the lib folder and it is not empty, so I had to remove empty subfolders and to run again **make install**.

I had to clear the empty subfolders in the lib and then to run again "make install" command.

**So, please be sure that the lib folder is empty.**

10x again for the awesome work!

**Comment by EngrPips** [comment]
Hello @Tezei, Thanks for pointing this out but the `discussion` tab is more appropriate for stuffs like this.
