### ISSUE TITLE
Two valid answers for a quiz on Foundry Fundamentals, Section 4.11 

### ISSUE THREAD

**Issue by yawarasuuna** [Cyfrin/foundry-full-course-cu#2809]
### Discussed in https://github.com/Cyfrin/foundry-full-course-cu/discussions/2768

<div type='discussions-op-text'>

<sup>Originally posted by **yawarasuuna** October 28, 2024</sup>
One of the question on Foundry Fundamentals, Section 4.11 for "Quiz: Smart Contract Lottery Intro", it asks "How can you use the modulo operator (%) to determine if a number is even or odd?"

![Screenshot 2024-10-28 at 15-38-07 Quiz Smart Contract Lottery Intro Cyfrin Updraft](https://github.com/user-attachments/assets/4e381de0-e2c2-4ce1-a83e-9af5d8d95986)

Wouldn't both answers B and C, in the example above, allow us to determine if a number is even or odd?

```
if n % 2 != 1 // If n is not odd ( n is even), otherwise it's odd
```

```
if n % 2 == 0 // If n is even, otherwise it's odd
```

From previous discussion linked above, it might indeed be true, and I wasn't hallucinating with the AI.

I believe this might be the correct repo with the challenges, but it is set to private on my side: https://github.com/Cyfrin/cyfrin-updraft-challenges-private

Thank you,</div>

**Comment by EngrPips** [comment]
Hello @yawarasuuna, Thanks for reporting this. It will be responded to appropriately as soon as possible.
