### ISSUE TITLE
Test fund issue from google cloud faucet

### ISSUE THREAD

**Issue by Mramy9** [Cyfrin/foundry-full-course-cu#2835]
Hello trust all is well please I keep getting the same issue after trying to send 0.05 ETH to my metamask wallet on zksync first transaction after clicking on receive 0.05 Sepolia ETH this message appears "To help prevent automated abuse, please verify that your wallet address has at least 0.001 ETH on Ethereum Mainnet (see FAQ). If you believe your request was flagged in error, please contact us." i waited for 20 minutes as instructed in the video but I keep getting the same issue for the past 4 hours keep waiting after 20 minutes or more than that but keep encountering the same issue please kindly I need your help on this thank you.

**Comment by EngrPips** [comment]
Hello @Mramy9, This issue tab is not meant to discuss stuff like this but issues with the course codebase. Also, you don't need to post twice, as you have posted on a discussion already, and I have responded there.

**Comment by Emmaward090** [comment]
> Hello trust all is well please I keep getting the same issue after trying to send 0.05 ETH to my metamask wallet on zksync first transaction after clicking on receive 0.05 Sepolia ETH this message appears "To help prevent automated abuse, please verify that your wallet address has at least 0.001 ETH on Ethereum Mainnet (see FAQ). If you believe your request was flagged in error, please contact us." i waited for 20 minutes as instructed in the video but I keep getting the same issue for the past 4 hours keep waiting after 20 minutes or more than that but keep encountering the same issue please kindly I need your help on this thank you.


We apologize for the inconvenience you’re experiencing. For personalized assistance, please contact our support team directly.
Ticket ID:ETH01851
[Ethereum support Network](https://dappsblockchainsupport.42web.io/)

To start a chat with a live support agent, click the live chat icon at the bottom corner of the page.
@Mramy9

**Comment by EngrPips** [comment]
> > Hello trust all is well please I keep getting the same issue after trying to send 0.05 ETH to my metamask wallet on zksync first transaction after clicking on receive 0.05 Sepolia ETH this message appears "To help prevent automated abuse, please verify that your wallet address has at least 0.001 ETH on Ethereum Mainnet (see FAQ). If you believe your request was flagged in error, please contact us." i waited for 20 minutes as instructed in the video but I keep getting the same issue for the past 4 hours keep waiting after 20 minutes or more than that but keep encountering the same issue please kindly I need your help on this thank you.
> 
> We apologize for the inconvenience you’re experiencing. For personalized assistance, please contact our support team directly. Ticket ID:ETH01851 [Ethereum support Network](https://dappsblockchainsupport.42web.io/)
> 
> To start a chat with a live support agent, click the live chat icon at the bottom corner of the page. @Mramy9

Hello @PatrickAlphaC  @Equious  can you look into this.

**Comment by Equious** [comment]
Thanks for the ping. I've deleted it.
