### ISSUE TITLE
A suggestion for a faucet section for chainlink faucets 

### ISSUE THREAD

**Issue by DevJSter** [Cyfrin/foundry-full-course-cu#2874]
### Describe the enhancement

This is the reason for you guys to add newer faucets because this chainlink's faucets is not working due to 1 Link token recquirement for them to send over the testnet
![image](https://github.com/user-attachments/assets/e9cd15b2-449f-485b-9819-6523dad4e3e1)

**Comment by EngrPips** [comment]
Thanks for the contribution @DevJSter, This will be attended to appropriately as soon as possible.

**Comment by DevJSter** [comment]
Only the Google Cloud Faucet is working fine tho and alchemy one also if you have funds😢

**Comment by EngrPips** [comment]
Yeah, getting eth sepolia has been a nightmare lately.

**Comment by serv-er** [comment]
yeah I was also getting problem to get sepolia testnet eth from chainlink faucets then I get that from google cloud faucet

**Comment by EngrPips** [comment]
Tough.
