### ISSUE TITLE
"introduction - foundry Simple Storage" subtitle is only english cc

### ISSUE THREAD

**Issue by kitezzzGrim** [Cyfrin/foundry-full-course-cu#2887]
### Section

Section 6 | Foundry Simple Storage

### Could you please leave a link to the Cyfrin Updraft Lesson (or YouTube video timestamp) where this error occurs? (You can right click a video and "copy video URL at current time")

https://updraft.cyfrin.io/courses/foundry/foundry-simple-storage/introduction-foundry-simple-storage

### Describe the bug

i find it only section 1 "introduction - foundry Simple Storage" subtitle is only english cc，others have multiple subtitles
<img width="1499" alt="Snipaste_2024-11-19_19-28-12" src="https://github.com/user-attachments/assets/85177847-8f46-458a-a500-311d45d99a91">
<img width="364" alt="Snipaste_2024-11-20_10-33-48" src="https://github.com/user-attachments/assets/fa4a9acc-ddad-4f2a-b901-23373e002893">

**Comment by EngrPips** [comment]
Thanks for raising this concern. This will be attended to appropriately as soon as possible.

**Comment by dev-araujo** [comment]
😭😭 Why??? Now that I've reached this part!!!!

**Comment by EngrPips** [comment]
@Equious, check this issue sir.

**Comment by dev-araujo** [comment]
:heart:
