### ISSUE TITLE
Mode error

### ISSUE THREAD

**Issue by mosheng-eng** [Cyfrin/foundry-full-course-cu#2926]
### Section

Section 9 | Smart Contract Lottery

### Describe the bug

![image](https://github.com/user-attachments/assets/5748c20c-f0cd-45f5-9bb5-60873d81593e)
this is a snapshot from course "Foundry Smart Contract Lottery". The mode result is not right.

**Comment by EngrPips** [comment]
Hello @mosheng-eng, Thanks for reporting this. It will be Looked into as soon as possible.
