### ISSUE TITLE
Foundry Fundamentals Course:: Lesson 29 - Wrong syntax in video name and video description

### ISSUE THREAD

**Issue by SquilliamX** [Cyfrin/foundry-full-course-cu#2931]
### Section

Section 9 | Smart Contract Lottery

### Could you please leave a link to the Cyfrin Updraft Lesson (or YouTube video timestamp) where this error occurs? (You can right click a video and "copy video URL at current time")

https://updraft.cyfrin.io/courses/foundry/smart-contract-lottery/vm-roll-warp

### Operating System

None

### Describe the bug

In Foundry Fundamentals Course:: Lesson 29, the video teaches users about `vm.warp`, however the video title and video description both spell this foundry cheatcode as `vm.wrap`. The foundry cheatcode is spelt wrong in the video title and video description.

**Comment by EngrPips** [comment]
Hello @SquilliamX, Thanks for pointing this out. This will be attended to appropriately as soon as possible.

**Comment by Equious** [comment]
Hey! Thanks for pointing this out! Should be adjusted in our next push to prod.
