### ISSUE TITLE
ZK Sync Foundry & M1 Mac Issues

### ISSUE THREAD

**Issue by JesseNovice** [Cyfrin/foundry-full-course-cu#3013]
### Discussed in https://github.com/Cyfrin/foundry-full-course-cu/discussions/3003

<div type='discussions-op-text'>

<sup>Originally posted by **JesseNovice** December  7, 2024</sup>
Hey Team,

Every time I try to run the command foundryup-zksync I get the below error. 

I am using brew on a silicon chip M2 2022 Mac Air.

I have tried upgrading my terminal with the ar64 as some errors and help forums & chatgpt said but I seem to be going in circles trying to get this working. Can someone help me please?

dyld[48910]: Library not loaded: /opt/homebrew/opt/libusb/lib/libusb-1.0.0.dylib
  Referenced from: <55CEFD02-5B6C-3AE2-8405-B96F31CE975B> /Users/jesselees/.foundry/bin/forge
  Reason: tried: '/opt/homebrew/opt/libusb/lib/libusb-1.0.0.dylib' (mach-o file, but is an incompatible architecture (have 'x86_64', need 'arm64e' or 'arm64')), '/System/Volumes/Preboot/Cryptexes/OS/opt/homebrew/opt/libusb/lib/libusb-1.0.0.dylib' (no such file), '/opt/homebrew/opt/libusb/lib/libusb-1.0.0.dylib' (mach-o file, but is an incompatible architecture (have 'x86_64', need 'arm64e' or 'arm64')), '/usr/local/Cellar/libusb/1.0.27/lib/libusb-1.0.0.dylib' (mach-o file, but is an incompatible architecture (have 'x86_64', need 'arm64e' or 'arm64')), '/System/Volumes/Preboot/Cryptexes/OS/usr/local/Cellar/libusb/1.0.27/lib/libusb-1.0.0.dylib' (no such file), '/usr/local/Cellar/libusb/1.0.27/lib/libusb-1.0.0.dylib' (mach-o file, but is an incompatible architecture (have 'x86_64', need 'arm64e' or 'arm64'))
foundryup-zksync: command failed: /Users/jesselees/.foundry/bin/forge --version
foundryup-zksync: installed - 
dyld[48913]: Library not loaded: /opt/homebrew/opt/libusb/lib/libusb-1.0.0.dylib
  Referenced from: <DB17DE42-455C-375D-AA69-00FA7EB5D3D9> /Users/jesselees/.foundry/bin/cast
  Reason: tried: '/opt/homebrew/opt/libusb/lib/libusb-1.0.0.dylib' (mach-o file, but is an incompatible architecture (have 'x86_64', need 'arm64e' or 'arm64')), '/System/Volumes/Preboot/Cryptexes/OS/opt/homebrew/opt/libusb/lib/libusb-1.0.0.dylib' (no such file), '/opt/homebrew/opt/libusb/lib/libusb-1.0.0.dylib' (mach-o file, but is an incompatible architecture (have 'x86_64', need 'arm64e' or 'arm64')), '/usr/local/Cellar/libusb/1.0.27/lib/libusb-1.0.0.dylib' (mach-o file, but is an incompatible architecture (have 'x86_64', need 'arm64e' or 'arm64')), '/System/Volumes/Preboot/Cryptexes/OS/usr/local/Cellar/libusb/1.0.27/lib/libusb-1.0.0.dylib' (no such file), '/usr/local/Cellar/libusb/1.0.27/lib/libusb-1.0.0.dylib' (mach-o file, but is an incompatible architecture (have 'x86_64', need 'arm64e' or 'arm64'))
foundryup-zksync: command failed: /Users/jesselees/.foundry/bin/cast --version
foundryup-zksync: installed - 
foundryup-zksync: done!

</div>

**Comment by EngrPips** [comment]
Hello @JesseNovice, Please use the #discussion  tab of this GitHub page to report this issue.
